import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import fetch from "isomorphic-unfetch";
import { Button, Card } from "semantic-ui-react";

const Home = ({ notes }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS MongoDB CRUD App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.noteContainer}>
        <h1>Notes</h1>
        <div className={styles.wrapper}>
          {notes.map((note) => (
            <div key={note._id}>
              <Card>
                <Card.Content>
                  <Card.Header>
                    <Link href={`/${note._id}`}>
                      <a>{note.title}</a>
                    </Link>
                  </Card.Header>
                </Card.Content>

                <Card.Content extra>
                  <Link href={`/${note._id}`}>
                    <Button primary>View</Button>
                  </Link>
                  <Link href={`/${note._id}/edit`}>
                    <Button primary>Edit</Button>
                  </Link>
                </Card.Content>
              </Card>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

Home.getInitialProps = async () => {
  const res = await fetch("http://localhost:3000/api/notes");
  const { data } = await res.json();

  return {
    notes: data,
  };
};

export default Home;
